name: Tests
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Optimised, shared, Python",
              os: ubuntu-18.04,
              configure_options: "--enable-shared
                                 --enable-checks=no
                                 --enable-optimize=3
                                 --disable-signal
                                 --disable-track
                                 --disable-backtrace
                                 --with-petsc
                                 --with-slepc
                                 --with-hdf5
                                 --with-sundials=/home/runner/local
                                 ",
              script_flags: "-uim -t shared -t python",
              pip_packages: "cython~=0.29 netcdf4~=1.5 sympy~=1.5",
            }
          - {
              name: "Debug, static",
              os: ubuntu-18.04,
              configure_options: "--enable-sigfpe
                                 --enable-debug
                                 --with-hdf5
                                 --with-petsc
                                 --with-slepc
                                 --with-sundials=/home/runner/local
                                 ",
              script_flags: "-uim",
              pip_packages: "cython~=0.29 netcdf4~=1.5 sympy~=1.5",
            }
    steps:
      - name: Install dependencies
        run: sudo apt update &&
             sudo apt install -y
                 libfftw3-dev
                 libnetcdf-dev
                 libnetcdf-c++4-dev
                 netcdf-bin
                 hdf5-tools
                 python3
                 python3-h5py
                 python3-pip
                 python3-pytest
                 python3-numpy
                 python3-scipy
                 lcov
                 libhdf5-mpi-dev
                 openmpi-bin
                 libopenmpi-dev
                 libpetsc3.7.7-dev
                 libslepc3.7.4-dev
                 liblapack-dev
                 libparpack2-dev

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install pip packages
        run: ./.pip_install_for_travis.sh ${{ matrix.config.pip_packages }}
        shell: bash

      - name: Cache SUNDIALS build
        uses: actions/cache@v2
        with:
          path: $HOME/local
          key: bout-sundials

      - name: Build SUNDIALS
        run: ./.build_sundials_for_travis.sh
        shell: bash

      - name: Build
        run: ./.travis_script.sh ${{ matrix.config.script_flags }}
        shell: bash
        env:
          LD_LIBRARY_PATH: /home/runner/local/lib:$LD_LIBRARY_PATH
          BOUT_TEST_TIMEOUT: "5m"
          CONFIGURE_OPTIONS: ${{ matrix.config.configure_options }}
          PETSC_DIR: /usr/lib/petscdir/3.7.7/x86_64-linux-gnu-real
          PETSC_ARCH: ""
          SLEPC_DIR: /usr/lib/slepcdir/3.7.4/x86_64-linux-gnu-real
          SLEPC_ARCH: ""

